disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - line_length
  - weak_delegate
  - force_cast
  - nesting
  - force_try
  - function_body_length
  - type_body_length
  - switch_case_alignment
  - cyclomatic_complexity

excluded:
  - SourcePackages
  - Export
  - app.xcarchive
  - test.xcresult