coverage:
  range: 10..60
  status:
    # do not run coverage on patch nor changes
    patch:
      default:
        enabled: false
    project:
      default:
        target: 14%
        informational: false
        only_pulls: false
        if_ci_failed: error
