name: "Setup Build Environment"
description: "Setup Xcode, Mint, and caches for macOS builds"

inputs:
  xcode-version:
    description: "Xcode version to use"
    required: false
    default: "26"
  cache-derived-data:
    description: "Whether to cache DerivedData"
    required: false
    default: "true"
  derived-data-key:
    description: "Key suffix for DerivedData cache"
    required: false
    default: "default"

runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Cache Homebrew
      uses: actions/cache@v4
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-mint
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Cache Mint packages
      uses: actions/cache@v4
      with:
        path: ~/.mint
        key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Install Mint and packages
      shell: bash
      run: |
        brew install mint 2>/dev/null || true
        mint bootstrap --link

    - name: Cache SPM packages
      uses: actions/cache@v4
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('Pareto Security.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Cache DerivedData
      if: inputs.cache-derived-data == 'true'
      uses: actions/cache@v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-deriveddata-${{ inputs.derived-data-key }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-deriveddata-${{ inputs.derived-data-key }}-
          ${{ runner.os }}-deriveddata-
