name: "Setup Build Environment"
description: "Setup Xcode, Mint, and caches for macOS builds"

inputs:
  xcode-version:
    description: "Xcode version to use"
    required: false
    default: "26"

runs:
  using: "composite"
  steps:
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ inputs.xcode-version }}

    - name: Cache Homebrew
      uses: actions/cache@v5
      with:
        path: |
          ~/Library/Caches/Homebrew
          /usr/local/Homebrew
        key: ${{ runner.os }}-homebrew-mint
        restore-keys: |
          ${{ runner.os }}-homebrew-

    - name: Cache Mint packages
      uses: actions/cache@v5
      with:
        path: ~/.mint
        key: ${{ runner.os }}-mint-${{ hashFiles('Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-

    - name: Install Mint and packages
      shell: bash
      run: |
        brew install mint 2>/dev/null || true
        mint bootstrap --link

    - name: Cache SPM packages
      uses: actions/cache@v5
      with:
        path: SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('Pareto Security.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
