name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Archive
    runs-on: macos-11
    timeout-minutes: 3
    permissions:
      issues: write 
      pull-requests: write
    steps:
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          You can find the built app under the Artifacts at https://github.com/ParetoSecurity/pareto-mac/actions/runs/${{ github.run_id }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        repo-token-user-login: 'github-actions[bot]'
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: "Import Certificate: Development"
      uses: devbotsxyz/xcode-import-certificate@master
      with:
        certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
        certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Cache SPM modules
      uses: actions/cache@v2
      env:
        cache-name: cache-spm
      with:
        path: SourcePackages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Pareto Security.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build
      run: make archive | xcpretty && exit ${PIPESTATUS[0]}
    - name: Compress app for storage
      run: ditto -V -c -k --keepParent Export/Pareto\ Security.app ParetoSecurity.app.zip
    - name: Upload App to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ParetoSecurity.app.zip
        path: ParetoSecurity.app.zip

