name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Archive
    runs-on: macos-11
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.0'
    - name: "Import Certificate: Development"
      uses: devbotsxyz/xcode-import-certificate@master
      with:
        certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
        certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
        keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Cache SPM modules
      uses: actions/cache@v2
      env:
        cache-name: cache-spm
      with:
        path: SourcePackages
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Pareto Security.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Build
      run: make build archive
    - name: Compress app for storage
      run: zip -r app.zip build/mac/Pareto\ Security.app
    - name: Upload App to Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app.zip
        path: app.zip
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - uses: mshick/add-pr-comment@v1
      with:
        message: |
          You can find the built app under the GitHub Action workflow https://github.com/ParetoSecurity/pareto-mac/actions/workflows/build.yml?query=branch:${{ steps.extract_branch.outputs.branch }}
        repo-token: ${{ secrets.RELEASE_SECRET }}
        repo-token-user-login: 'github-actions[bot]'